name: Auto Approval POF - 2

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited]

jobs:
  onboard_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            console.log(context.payload);

            github.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,          // org
              repo: context.payload.repository.name,                  // inventory
              pull_number: context.payload.number,
              event: 'APPROVE'
            });
