name: Auto Approval POF

on:
  pull_request:
    types: 
      - opened
    branches:
      - 'users/altera-approver/**'

jobs:
  onboard_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            console.log(context.payload);
