name: Auto Approval POF

on:
  issues:
    types: [opened]

jobs:
  onboard_repos:
    runs-on: ubuntu-latest
    steps:
      - name: Facilitate PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            // Initialize Variables
            const org = 'jaron-bauers';       // inner-source
            const repo = 'inventory-2';       // inventory
            const baseBranch = 'main';
            const head = context.payload.issue.body;
            
            // Create PR
            const prResponse = await github.rest.pulls.create({
              owner: org,
              repo,
              title: 'Facilitate [Enter Team Name] PR',
              body: `Facilitating branch ${context.payload.issue.body} PR creation\n\nCloses ${context.payload.repository.full_name}#${context.issue.number}`,
              head,
              base: baseBranch,
            });

            // Comment to issue with PR status
            github.rest.issues.createComment({
              owner: org,
              repo: context.payload.repository.name,
              issue_number: context.issue.number,
              body: `Here is the link to your PR: ${prResponse.data.html_url}`,
            });

            // Enable auto-merge for PR
            await github.graphql({
              query: `
                mutation($pullRequestId: ID!) {
                  enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: MERGE}) {
                    pullRequest {
                      autoMergeRequest {
                        enabledAt
                      }
                    }
                  }
                }
              `,
              pullRequestId: prResponse.data.node_id
            });
